# Generated automatically from Makefile.in by configure.
CUR_DEPTH	= ../../../
CPPFLAGS	= -O6 -I$(CUR_DEPTH)/include
OBJS		= ansi2knr.o \
		  ansi2knr.o \
		  jcinit.o \
		  jdatadst.o \
		  jdpostct.o \
		  rdjpgcom.o \
		  jcmainct.o \
		  jdatasrc.o \
		  jdsample.o \
		  rdppm.o \
		  jcmarker.o \
		  jdcoefct.o \
		  jdtrans.o \
		  jmemmgr.o \
		  rdrle.o \
		  ckconfig.o \
		  jcmaster.o \
		  jdcolor.o \
		  jerror.o \
		  jmemname.o \
		  rdswitch.o \
		  djpeg.o \
		  jcomapi.o \
		  jddctmgr.o \
		  jfdctflt.o \
		  jmemnobs.o \
		  rdtarga.o \
		  jcparam.o \
		  jdhuff.o \
		  jfdctfst.o \
		  jpegtran.o \
		  transupp.o \
		  jcapimin.o \
		  jcphuff.o \
		  jdinput.o \
		  jfdctint.o \
		  jquant1.o \
		  wrbmp.o \
		  jcapistd.o \
		  jcprepct.o \
		  jdmainct.o \
		  jidctflt.o \
		  jquant2.o \
		  wrgif.o \
		  jccoefct.o \
		  jcsample.o \
		  jdmarker.o \
		  jidctfst.o \
		  jutils.o \
		  wrjpgcom.o \
		  jccolor.o \
		  jctrans.o \
		  jdmaster.o \
		  jidctint.o \
		  rdbmp.o \
		  wrppm.o \
		  jcdctmgr.o \
		  jdapimin.o \
		  jdmerge.o \
		  jidctred.o \
		  rdcolmap.o \
		  wrrle.o \
		  jchuff.o \
		  jdapistd.o \
		  jdphuff.o \
		  jmemansi.o \
		  rdgif.o \
		  wrtarga.o


all: .depend $(OBJS)
	

clean: ;	rm -f *.o
	rm -f .depend

.depend: $(OBJS:.o=.c)
	$(CC) -M $(CPPFLAGS) $(OBJS:.o=.c) > .depend 

include .depend
