PROG		= play_avi
CUR_DEPTH	= ../../../
CPPFLAGS	=  -I$(CUR_DEPTH)/include -g -DSCREEN_DEPTH=$(SD) \
                  


OBJS		=  main.o
LIBS		= -L$(CUR_DEPTH)/lib -lXVDevs -lXVCons  -lXVImages\
		  -lavcodec -lavformat -lswscale  \
		    -lpthread 

# if you want to set the screen depth explicitly,
# do it here.  Otherwise, the depth of the screen 
# used to compile XVision2 (the screen you type "make" in)
# will be determined and used.
SD = $(shell $(CUR_DEPTH)/bin/screendepth)

all: .depend $(OBJS)
	$(CXX)  -o $(PROG) $(OBJS) $(LIBS) -lm

clean: ;	rm -f *.o
		rm -f $(PROG) .depend

.depend: $(OBJS:.o=.cc)
	$(CC) -M  $(CPPFLAGS) $(OBJS:.o=.cc) > .depend

install: all
	install -c $(PROG) $(CUR_DEPTH)/bin

include .depend
