.TH XVColorBase 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVColorBase \- base class for color images? 
.SH SYNOPSIS
.br
.PP
\fC#include <XVColorImage.h>\fR
.PP
Inherits \fBXVImageBase< T >\fR, and \fBXVColorImage\fR.
.PP
Inherited by \fBXVImageHSV\fR\fC [virtual]\fR, \fBXVImageRGB\fR, and \fBXVImageYUV\fR\fC [virtual]\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVColorBase\fR (const int w, const int h, XVPixmap<T> * pix = NULL)"
.br
.ti -1c
.RI "\fBXVColorBase\fR (const \fBXVSize\fR & s, XVPixmap<T> * pix = NULL)"
.br
.ti -1c
.RI "\fBXVColorBase\fR (const \fBXVImageGeneric\fR & im, XVPixmap<T> * pix = NULL)"
.br
.ti -1c
.RI "\fBXVColorBase\fR (const XVColorBase<T> & im)"
.br
.ti -1c
.RI "\fBXVColorBase\fR (XVPixmap<T> * pix)"
.br
.ti -1c
.RI "\fBXVColorBase\fR ()"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageYUV\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageYUV422\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageHSV\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class XVColorBase
base class for color images?
.PP
Definition at line 53 of file XVColorImage.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT> XVColorBase<T>::XVColorBase<T> (const int w, const int h, XVPixmap< T >* pix = NULL)
.PP
Definition at line 57 of file XVColorImage.h.
.SS template<classT> XVColorBase<T>::XVColorBase<T> (const \fBXVSize\fR & s, XVPixmap< T >* pix = NULL)
.PP
Definition at line 58 of file XVColorImage.h.
.SS template<classT> XVColorBase<T>::XVColorBase<T> (const \fBXVImageGeneric\fR & im, XVPixmap< T >* pix = NULL)
.PP
Definition at line 59 of file XVColorImage.h.
.SS template<classT> XVColorBase<T>::XVColorBase<T> (const XVColorBase< T >& im)
.PP
Definition at line 60 of file XVColorImage.h.
.SS template<classT> XVColorBase<T>::XVColorBase<T> (XVPixmap< T >* pix)
.PP
Definition at line 61 of file XVColorImage.h.
.SS template<classT> XVColorBase<T>::XVColorBase<T> ()
.PP
Definition at line 62 of file XVColorImage.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.