.TH XVColorImage 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVColorImage \- The purpose of this class is to allow implicit conversions between different image types, when such a conversion is required. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVColorImage.h>\fR
.PP
Inherited by \fBXVColorBase\fR\fC [virtual]\fR, and \fBXVImageYUV422\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageRGB\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageYUV\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageHSV\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageYUV422\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.ti -1c
.RI "virtual \fBoperator XVImageScalar\fR () const = 0"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
The purpose of this class is to allow implicit conversions between different image types, when such a conversion is required.
.PP
If no conversion is required, no conversion is done. 
.PP
Definition at line 25 of file XVColorImage.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.