.TH XVDrawPointX 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVDrawPointX \- point object for \fBXVDrawWindowX\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVWindowX.h>\fR
.PP
Inherits \fBXVDrawPoint\fR, and \fBXVDrawObjectX\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVDrawPointX\fR (Display * d, Window w, GC g, XVPosition p, \fBXVDrawColor\fR c = DEFAULT_COLOR)"
.br
.ti -1c
.RI "virtual \fB~XVDrawPointX\fR ()"
.br
.ti -1c
.RI "virtual void \fBdraw\fR ()"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
point object for \fBXVDrawWindowX\fR.
.PP
Definition at line 523 of file XVWindowX.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVDrawPointX::XVDrawPointX (Display * d, Window w, GC g, XVPosition p, \fBXVDrawColor\fR c = DEFAULT_COLOR)
.PP
Definition at line 527 of file XVWindowX.h.
.SS XVDrawPointX::~XVDrawPointX ()\fC [inline, virtual]\fR
.PP
Definition at line 531 of file XVWindowX.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void XVDrawPointX::draw ()\fC [inline, virtual]\fR
.PP
Reimplemented from \fBXVDrawObject\fR.
.PP
Definition at line 533 of file XVWindowX.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.