.TH XVDrawEllipseX 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVDrawEllipseX \- ellipse object for \fBXVDrawWindowX\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVWindowX.h>\fR
.PP
Inherits \fBXVDrawEllipse\fR, and \fBXVDrawObjectX\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVDrawEllipseX\fR (Display * d, Window w, GC g, \fBXVImageGeneric\fR r, bool f = false, \fBXVDrawColor\fR c = DEFAULT_COLOR)"
.br
.ti -1c
.RI "virtual \fB~XVDrawEllipseX\fR ()"
.br
.ti -1c
.RI "virtual void \fBdraw\fR ()"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
ellipse object for \fBXVDrawWindowX\fR.
.PP
Definition at line 585 of file XVWindowX.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVDrawEllipseX::XVDrawEllipseX (Display * d, Window w, GC g, \fBXVImageGeneric\fR r, bool f = false, \fBXVDrawColor\fR c = DEFAULT_COLOR)
.PP
Definition at line 589 of file XVWindowX.h.
.SS XVDrawEllipseX::~XVDrawEllipseX ()\fC [inline, virtual]\fR
.PP
Definition at line 593 of file XVWindowX.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS void XVDrawEllipseX::draw ()\fC [inline, virtual]\fR
.PP
Reimplemented from \fBXVDrawObject\fR.
.PP
Definition at line 595 of file XVWindowX.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.