.TH XVDrawEllipse 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVDrawEllipse \- class for drawing an ellipse in XVWindows. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVDrawable.h>\fR
.PP
Inherits \fBXVDrawObject\fR.
.PP
Inherited by \fBXVDrawEllipseX\fR\fC [virtual]\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVDrawEllipse\fR (\fBXVImageGeneric\fR r, bool f = false, \fBXVDrawColor\fR c = DEFAULT_COLOR)"
.br
.ti -1c
.RI "virtual \fB~XVDrawEllipse\fR ()"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "bool \fBfill\fR"
.br
.ti -1c
.RI "\fBXVImageGeneric\fR \fBregion\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
class for drawing an ellipse in XVWindows.
.PP
Definition at line 103 of file XVDrawable.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVDrawEllipse::XVDrawEllipse (\fBXVImageGeneric\fR r, bool f = false, \fBXVDrawColor\fR c = DEFAULT_COLOR)
.PP
Definition at line 110 of file XVDrawable.h.
.SS XVDrawEllipse::~XVDrawEllipse ()\fC [inline, virtual]\fR
.PP
Definition at line 112 of file XVDrawable.h.
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS bool XVDrawEllipse::fill
.PP
Definition at line 107 of file XVDrawable.h.
.SS \fBXVImageGeneric\fR XVDrawEllipse::region
.PP
Definition at line 108 of file XVDrawable.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.