.TH XVImageException 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVImageException \- exception class for XVImages. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVImageBase.h>\fR
.PP
Inherits \fBXVException\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVImageException\fR ()"
.br
.ti -1c
.RI "\fBXVImageException\fR (char * err)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
exception class for XVImages.
.PP
Definition at line 20 of file XVImageBase.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVImageException::XVImageException ()
.PP
Definition at line 21 of file XVImageBase.h.
.SS XVImageException::XVImageException (char * err)
.PP
Definition at line 22 of file XVImageBase.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.