.TH XVImageRGB 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVImageRGB \- class for RGB images. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVImageRGB.h>\fR
.PP
Inherits \fBXVColorBase< T >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVImageRGB\fR (int width, int height, XVPixmap<T> * \fBpixmap\fR = NULL)"
.br
.ti -1c
.RI "\fBXVImageRGB\fR (\fBXVSize\fR s, XVPixmap<T> * p )"
.br
.ti -1c
.RI "\fBXVImageRGB\fR (XVPixmap<T> * \fBpixmap\fR)"
.br
.ti -1c
.RI "\fBXVImageRGB\fR ()"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class XVImageRGB
class for RGB images.
.PP
Definition at line 18 of file XVImageRGB.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT> XVImageRGB<T>::XVImageRGB<T> (int width, int height, XVPixmap< T >* pixmap = NULL)
.PP
Definition at line 22 of file XVImageRGB.h.
.SS template<classT> XVImageRGB<T>::XVImageRGB<T> (\fBXVSize\fR s, XVPixmap< T >* p)
.PP
Definition at line 24 of file XVImageRGB.h.
.SS template<classT> XVImageRGB<T>::XVImageRGB<T> (XVPixmap< T >* pixmap)
.PP
Definition at line 27 of file XVImageRGB.h.
.SS template<classT> XVImageRGB<T>::XVImageRGB<T> ()
.PP
Definition at line 28 of file XVImageRGB.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.