.TH XVImageHSV 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVImageHSV \- class for HSV images. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVImageHSV.h>\fR
.PP
Inherits \fBXVColorBase< T >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVImageHSV\fR (int width, int height, XVPixmap<T> * \fBpixmap\fR = NULL)"
.br
.ti -1c
.RI "\fBXVImageHSV\fR (\fBXVSize\fR s, XVPixmap<T> * p )"
.br
.ti -1c
.RI "\fBXVImageHSV\fR (XVPixmap<T> * \fBpixmap\fR)"
.br
.ti -1c
.RI "\fBXVImageHSV\fR ()"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T>  template class XVImageHSV
class for HSV images.
.PP
Definition at line 21 of file XVImageHSV.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT> XVImageHSV<T>::XVImageHSV<T> (int width, int height, XVPixmap< T >* pixmap = NULL)
.PP
Definition at line 25 of file XVImageHSV.h.
.SS template<classT> XVImageHSV<T>::XVImageHSV<T> (\fBXVSize\fR s, XVPixmap< T >* p)
.PP
Definition at line 27 of file XVImageHSV.h.
.SS template<classT> XVImageHSV<T>::XVImageHSV<T> (XVPixmap< T >* pixmap)
.PP
Definition at line 30 of file XVImageHSV.h.
.SS template<classT> XVImageHSV<T>::XVImageHSV<T> ()
.PP
Definition at line 31 of file XVImageHSV.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.