.TH XVImageYUV422 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVImageYUV422 \- class for YUV422 images. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVImageYUV422.h>\fR
.PP
Inherits \fBXVImageBase< XV_YUV422 >\fR, and \fBXVColorImage\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVImageYUV422\fR (const int width, const int height, XVPixmap<XV_YUV422> * \fBpixmap\fR = NULL)"
.br
.ti -1c
.RI "\fBXVImageYUV422\fR (const \fBXVSize\fR s, XVPixmap<XV_YUV422> * p )"
.br
.ti -1c
.RI "\fBXVImageYUV422\fR (const \fBXVImageGeneric\fR & im, XVPixmap<XV_YUV422> * pix = NULL)"
.br
.ti -1c
.RI "\fBXVImageYUV422\fR (const XVImageYUV422 & im)"
.br
.ti -1c
.RI "\fBXVImageYUV422\fR (XVPixmap<XV_YUV422> * \fBpixmap\fR)"
.br
.ti -1c
.RI "\fBXVImageYUV422\fR ()"
.br
.ti -1c
.RI "\fBXVImageBase\fR<XV_YUV422> \fBnewImage\fR ()"
.br
.ti -1c
.RI "\fBXVImageBase\fR<XV_YUV422> \fBnewImage\fR (int w, int h)"
.br
.ti -1c
.RI "\fBXVImageBase\fR<XV_YUV422> \fBnewImage\fR (\fBXVSize\fR s)"
.br
.ti -1c
.RI "\fBXVImageBase\fR<XV_YUV422> \fBnewImage\fR (XVPixmap<XV_YUV422> * p )"
.br
.ti -1c
.RI "\fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageRGB\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageYUV\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageYUV422\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageHSV\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.ti -1c
.RI "\fBoperator XVImageScalar\fR () const"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
class for YUV422 images.
.PP
Definition at line 13 of file XVImageYUV422.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVImageYUV422::XVImageYUV422 (const int width, const int height, XVPixmap< XV_YUV422 >* pixmap = NULL)
.PP
Definition at line 17 of file XVImageYUV422.h.
.SS XVImageYUV422::XVImageYUV422 (const \fBXVSize\fR s, XVPixmap< XV_YUV422 >* p)
.PP
Definition at line 19 of file XVImageYUV422.h.
.SS XVImageYUV422::XVImageYUV422 (const \fBXVImageGeneric\fR & im, XVPixmap< XV_YUV422 >* pix = NULL)
.PP
Definition at line 21 of file XVImageYUV422.h.
.SS XVImageYUV422::XVImageYUV422 (const XVImageYUV422 & im)
.PP
Definition at line 22 of file XVImageYUV422.h.
.SS XVImageYUV422::XVImageYUV422 (XVPixmap< XV_YUV422 >* pixmap)
.PP
Definition at line 24 of file XVImageYUV422.h.
.SS XVImageYUV422::XVImageYUV422 ()
.PP
Definition at line 25 of file XVImageYUV422.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS \fBXVImageBase\fR< XV_YUV422 > XVImageYUV422::newImage<XV_YUV422> ()\fC [inline]\fR
.PP
Definition at line 27 of file XVImageYUV422.h.
.SS \fBXVImageBase\fR< XV_YUV422 > XVImageYUV422::newImage<XV_YUV422> (int w, int h)\fC [inline]\fR
.PP
Definition at line 28 of file XVImageYUV422.h.
.SS \fBXVImageBase\fR< XV_YUV422 > XVImageYUV422::newImage<XV_YUV422> (\fBXVSize\fR s)\fC [inline]\fR
.PP
Definition at line 29 of file XVImageYUV422.h.
.SS \fBXVImageBase\fR< XV_YUV422 > XVImageYUV422::newImage<XV_YUV422> (XVPixmap< XV_YUV422 >* p)\fC [inline]\fR
.PP
Definition at line 30 of file XVImageYUV422.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.