.TH XVNode 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVNode \- XVnode class. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVList.h>\fR
.PP
Inherited by XVFeature, and \fBXVImageBase\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVNode\fR ()"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "XVNode* \fBsucc\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
XVnode class.
.PP
This is a simple node in a linked list (\fBXVList\fR). Each node in a given list represent the images (\fBXVImageBase\fR) that share the same pixmap (XVPixmap) 
.PP
Definition at line 16 of file XVList.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVNode::XVNode ()\fC [inline]\fR
.PP
Definition at line 22 of file XVList.h.
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS XVNode * XVNode::succ
.PP
Definition at line 20 of file XVList.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.