.TH XVScalarRangeSeg 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVScalarRangeSeg \- segmentation based on scalar range values. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVScalarSeg.h>\fR
.PP
Inherits \fBXVSegmentation< T,Y >\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVScalarRangeSeg\fR (dispLims<T> & set_range)"
.br
.ti -1c
.RI "\fB~XVScalarRangeSeg\fR ()"
.br
.ti -1c
.RI "void \fBupdate\fR (const \fBXVImageBase\fR<T>&)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 

.SS template<class T, class Y>  template class XVScalarRangeSeg
segmentation based on scalar range values.
.PP
Definition at line 33 of file XVScalarSeg.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS template<classT, classY> XVScalarRangeSeg<T, Y>::~XVScalarRangeSeg<T, Y> ()\fC [inline]\fR
.PP
Definition at line 42 of file XVScalarSeg.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS template<classT, classY> void XVScalarRangeSeg<T, Y>::update (const \fBXVImageBase\fR< T >& roiIM)\fC [inline, virtual]\fR
.PP
Reimplemented from \fBXVSegmentation\fR.
.PP
Definition at line 43 of file XVScalarSeg.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.