.TH XVTrackerException 3 "26 Oct 2007" "XVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XVTrackerException \- XVFeature.h. 
.SH SYNOPSIS
.br
.PP
\fC#include <XVFeature.h>\fR
.PP
Inherits \fBXVException\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBXVTrackerException\fR ()"
.br
.ti -1c
.RI "\fBXVTrackerException\fR ( char * err )"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
XVFeature.h.
.PP
\fBAuthor(s): \fR
.in +1c
 Sam Lang 
.PP
\fBVersion: \fR
.in +1c
 
.PP
\fBId: \fR XVFeature.h,v 1.29 2004/09/08 22:47:16 cvsuser Exp  
.PP
Definition at line 16 of file XVFeature.h.
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS XVTrackerException::XVTrackerException ()
.PP
Definition at line 17 of file XVFeature.h.
.SS XVTrackerException::XVTrackerException (char * err)
.PP
Definition at line 18 of file XVFeature.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for XVision from the source code.