CUR_DEPTH	= ../../..
CXXFLAGS        = -O6 -pipe -DDEBUG_LEVEL=1 -DHAVE_CONFIG_H
CPPFLAGS	= -I$(CUR_DEPTH)/include
OBJS		= XVBlobFeature.o

all: .depend $(OBJS)

clean: ;	rm -f *.o
	        rm -f .depend

.depend: $(OBJS:.o=.cc)
	$(CC) -M $(CPPFLAGS) $(OBJS:.o=.cc) > .depend 

include .depend

